apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-consumer
  labels:
    app: polaris-consumer
spec:
  replicas: 1  # Apenas um pod será criado
  selector:
    matchLabels:
      app: polaris-consumer
  template:
    metadata:
      labels:
        app: polaris-consumer
    spec:
      containers:
        - name: consumer
          image: caiovsk/consumer:latest  # Certifique-se de que a imagem está no Docker Hub
          ports:
            - containerPort: 80  # Porta padrão (se necessário)
          env:  # Configurações de ambiente, incluindo o RabbitMQ
            - name: RabbitMQ__Host
              value: "rabbitmq"
            - name: RabbitMQ__Port
              value: "5672"
            - name: RabbitMQ__Username
              value: "guest"
            - name: RabbitMQ__Password
              value: "guest"
            - name: DbSettings__ConnectionString
              value: "Data Source=sql-server,1433;Initial Catalog=PolarisContacts;Persist Security Info=True;User ID=sa;Password=YourStrongPassword!;"