apiVersion: v1
kind: Service
metadata:
  name: polaris-consumer
spec:
  selector:
    app: polaris-consumer
  ports:
    - protocol: TCP
      port: 80       # Porta exposta pelo serviço
      targetPort: 80 # Porta do contêiner
  type: ClusterIP
